#!/usr/bin/env python3
"""Multi-model reading harness for the "read by any model" result (paper Section 4.3).

Holds the substrate (GOLGI structure), the question set, and the judge FIXED, and
swaps ONLY the reading agent across a config-driven list of models. Produces a
per-model accuracy table (Markdown + a LaTeX stub) ready for the paper.

This is a wrapper over the existing T1 bench (`golgi bench t1 run`), which routes the
answer/reading model via the PWMBENCH_SYNTH_MODEL env var and holds the judge model
fixed. It fabricates no numbers: every value comes from the per-run `-summary.json`
the bench writes. Models that have not been run yet appear as TODO rows.

Usage:
  uv run python scripts/paper/multimodel_reading_harness.py \
      --tasks docs/research/pwm-bench-t1-hana-questions.jsonl \
      --data-root /path/to/golgi-bench-data \
      --judge gemini-2.5-flash \
      --models gemini-3.5-flash gemini-2.5-pro gpt-4o gemma3:4b qwen3-vl:4b \
      --out benchmarks/results/t1/multimodel

Only the reading model varies. System is fixed to `pwm`; questions, structure, and
judge are identical across rows. That isolation is the "read by any model" claim.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

CATEGORIES = [
    "specific_events",  # NOTE: verify against the task file's actual category keys;
    "recurring_patterns",  # the current T1 set uses: counterfactual, lifetime_spans,
    "lifetime_spans",  # multi_source, open_ended, recurring_patterns. See summary flag.
    "multi_source",
    "counterfactual",
]


def run_one(model: str, tasks: str, data_root: str, judge: str, out_dir: Path) -> Path:
    """Run the T1 bench for system=pwm with `model` as the reading agent; judge fixed."""
    out_csv = out_dir / f"read-{model.replace('/', '_').replace(':', '_')}.csv"
    env = dict(os.environ)
    env["PWMBENCH_SYNTH_MODEL"] = model            # the reading/answer model (swapped)
    env["PWMBENCH_JUDGE_MODEL"] = judge            # judge held fixed across all rows
    env["GOOGLE_GENAI_USE_VERTEXAI"] = env.get("GOOGLE_GENAI_USE_VERTEXAI", "false")
    cmd = [
        "uv", "run", "golgi", "bench", "t1", "run",
        "--tasks", tasks,
        "--systems", "pwm",                        # substrate fixed to GOLGI
        "--data-root", data_root,
        "--output", str(out_csv),
    ]
    print(f"[read-model={model}] {' '.join(cmd)}", file=sys.stderr)
    subprocess.run(cmd, env=env, check=True)
    return out_csv.with_name(out_csv.stem + "-summary.json")


def read_summary(summary_path: Path) -> dict | None:
    """Pull pwm overall + per-category correctness from a bench -summary.json. No fabrication."""
    if not summary_path.exists():
        return None
    data = json.loads(summary_path.read_text())
    sys_block = (data.get("per_system") or {}).get("pwm")
    if not sys_block:
        return None
    per_cat = {k: v.get("correctness_mean") for k, v in (sys_block.get("per_category") or {}).items()}
    return {
        "overall": sys_block.get("correctness_mean"),
        "grounding": sys_block.get("grounding_rate"),
        "hallucination": sys_block.get("hallucination_rate"),
        "per_category": per_cat,
    }


def emit_markdown(rows: dict[str, dict | None], out_dir: Path) -> None:
    cats = sorted({c for r in rows.values() if r for c in (r["per_category"] or {})})
    header = ["reading model", "overall", *cats, "grounding", "halluc."]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for model, r in rows.items():
        if r is None:
            lines.append(f"| {model} | TODO (not yet run) |" + " |".join([""] * (len(header) - 1)))
            continue
        cells = [model, _fmt(r["overall"])]
        cells += [_fmt((r["per_category"] or {}).get(c)) for c in cats]
        cells += [_fmt(r["grounding"]), _fmt(r["hallucination"])]
        lines.append("| " + " | ".join(cells) + " |")
    (out_dir / "read_by_any_model.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


def emit_latex(rows: dict[str, dict | None], out_dir: Path) -> None:
    """LaTeX table stub for the paper. Rows without data emit \\todo, never a fake number."""
    body = []
    for model, r in rows.items():
        if r is None:
            body.append(f"{_tex(model)} & \\todo{{run}} \\\\")
        else:
            body.append(f"{_tex(model)} & {_fmt(r['overall'])} \\\\")
    tex = (
        "% Auto-generated by multimodel_reading_harness.py. Do not hand-edit numbers.\n"
        "\\begin{table}[t]\\centering\\small\n"
        "\\begin{tabular}{lr}\n\\toprule\n"
        "Reading model & Correctness \\\\\n\\midrule\n"
        + "\n".join(body) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{The same GOLGI structure, questions, and judge, read by different "
        "models. Only the reading agent varies.}\n\\label{tab:read-any-model}\n\\end{table}\n"
    )
    (out_dir / "read_by_any_model.tex").write_text(tex)


def _fmt(x) -> str:
    return "" if x is None else (f"{x:.1f}" if isinstance(x, (int, float)) else str(x))


def _tex(s: str) -> str:
    return s.replace("_", "\\_")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tasks", required=True)
    ap.add_argument("--data-root", required=True)
    ap.add_argument("--judge", default="gemini-2.5-flash")
    ap.add_argument("--models", nargs="+", required=True)
    ap.add_argument("--out", default="benchmarks/results/t1/multimodel")
    ap.add_argument("--skip-run", action="store_true",
                    help="Aggregate existing -summary.json files without re-running the bench.")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: dict[str, dict | None] = {}
    for model in args.models:
        summary = out_dir / f"read-{model.replace('/', '_').replace(':', '_')}-summary.json"
        if not args.skip_run:
            try:
                summary = run_one(model, args.tasks, args.data_root, args.judge, out_dir)
            except subprocess.CalledProcessError as e:
                print(f"[read-model={model}] FAILED: {e}", file=sys.stderr)
                rows[model] = None
                continue
        rows[model] = read_summary(summary)

    emit_markdown(rows, out_dir)
    emit_latex(rows, out_dir)
    print(f"\nWrote {out_dir}/read_by_any_model.md and .tex", file=sys.stderr)


if __name__ == "__main__":
    main()
